### ISSUE TITLE
[BUG]: module 'colour' has no attribute 'apply_matrix_colour_correction'

### ISSUE THREAD

**Issue by materialjan** [colour-science/colour#1186]
### Description

Hello I've encountered a problem
Installed through :
conda install -c conda-forge colour-science
Got 0.4.2 version which is listed as alpha
When running the example here :
https://colour.readthedocs.io/en/develop/generated/colour.apply_matrix_colour_correction.html#colour.apply_matrix_colour_correction
I get an error : module 'colour' has no attribute 'apply_matrix_colour_correction'

While computing  a matrix using the doc example works.
https://colour.readthedocs.io/en/develop/generated/colour.matrix_colour_correction.html#colour.matrix_colour_correction

It sounds like a silly error but the two examples diverge. And can't explain why.

Also worth noting I had to install colour-checker-detection with pip
pip install --user colour-checker-detection

Thank you.
[EDIT: version listed here is 0.4.1 because I tried to downgrade, but same thing happen in 0.4.2]
### Code for Reproduction

```python
RGB = np.array([0.17224810, 0.09170660, 0.06416938])
CCM = np.array(
    [
        [1.05263767, 0.13780789, -0.22763399],
        [0.07395843, 1.02939945, -0.1060115],
        [0.05725508, -0.20526336, 1.10151945],
    ]
)
apply_matrix_colour_correction(RGB, CCM)
```

### Exception Message

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/macbook/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/colour/__init__.py", line 874, in __getattr__
    return super().__getattr__(attribute)
  File "/Users/macbook/opt/anaconda3/envs/myenv/lib/python3.9/site-packages/colour/utilities/deprecation.py", line 374, in __getattr__
    return getattr(self._module, attribute)
AttributeError: module 'colour' has no attribute 'apply_matrix_colour_correction'
```

### Environment Information

```shell
import colour; colour.utilities.describe_environment()
===============================================================================
*                                                                             *
*   Interpreter :                                                             *
*       python : 3.9.7 (default, Sep 16 2021, 08:50:36)                       *
*                [Clang 10.0.0 ]                                              *
*                                                                             *
*   colour-science.org :                                                      *
*       colour : 0.4.1                                                        *
*                                                                             *
*   Runtime :                                                                 *
*       imageio : 2.31.1                                                      *
*       matplotlib : 3.7.1                                                    *
*       networkx : 2.8.4                                                      *
*       numpy : 1.21.2                                                        *
*       scipy : 1.7.1                                                         *
*       sklearn : 1.2.2                                                       *
*       OpenImageIO : 2.2.18                                                  *
*                                                                             *
===============================================================================
defaultdict(<class 'dict'>, {'Interpreter': {'python': '3.9.7 (default, Sep 16 2021, 08:50:36) \n[Clang 10.0.0 ]'}, 'colour-science.org': {'colour': '0.4.1'}, 'Runtime': {'imageio': '2.31.1', 'matplotlib': '3.7.1', 'networkx': '2.8.4', 'numpy': '1.21.2', 'scipy': '1.7.1', 'sklearn': '1.2.2', 'OpenImageIO': '2.2.18'}})
```

**Comment by KelSolaar** [comment]
Hi @materialjan,

This is an unreleased feature from the `develop` branch. Hopefully released in the coming weeks.

Cheers,

Thomas
