### ISSUE TITLE
[BUG]: Unable to use the `colour.RGB_to_XYZ` definition.

### ISSUE THREAD

**Issue by BQ-Octantis** [colour-science/colour#1205]
### Description

Hello,

I have successfully done numerous sRGB_to_XYZ transformations and am now trying to do a generalized RGB_to_XYZ transformation (say, for Adobe RGB).

But when I follow the [example in the RTFM](https://colour.readthedocs.io/en/v0.4.2/generated/colour.RGB_to_XYZ.html) exactly, I get an error that 'Bradford' couldn't be converted from string to float.

I have tried numerous changes to the input, but this appears to be some flow problem under the hood. I have used numerous other functions without issue, so it is the only feature affected.

Any help would be appreciated.

Cheers,

BQ

### Code for Reproduction

```python
import colour
import numpy as np
from colour.models import RGB_COLOURSPACE_sRGB
RGB = np.array([0.45595571, 0.03039702, 0.04087245])
illuminant = np.array([0.34570, 0.35850])
colour.RGB_to_XYZ(RGB, "sRGB", illuminant, "Bradford")
```

### Exception Message

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/BQ_Octantis/Library/Python/3.11/lib/python/site-packages/colour/models/rgb/rgb_colourspace.py", line 1163, in RGB_to_XYZ
    XYZ = vector_dot(matrix_RGB_to_XYZ, RGB)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/BQ_Octantis/Library/Python/3.11/lib/python/site-packages/colour/algebra/common.py", line 614, in vector_dot
    return np.einsum("...ij,...j->...i", as_float_array(m), as_float_array(v))
                                         ^^^^^^^^^^^^^^^^^
  File "/Users/BQ_Octantis/Library/Python/3.11/lib/python/site-packages/colour/utilities/array.py", line 723, in as_float_array
    return as_array(a, dtype)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/BQ_Octantis/Library/Python/3.11/lib/python/site-packages/colour/utilities/array.py", line 564, in as_array
    return np.asarray(a, dtype)
           ^^^^^^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'Bradford'
```

### Environment Information

```shell
===============================================================================
*                                                                             *
*   Interpreter :                                                             *
*       python : 3.11.3 (main, Apr  9 2023, 16:36:12) [Clang 10.0.0           *
*   (clang-1000.10.44.4)]                                                     *
*                                                                             *
*   colour-science.org :                                                      *
*       colour : 0.4.2                                                        *
*                                                                             *
*   Runtime :                                                                 *
*       imageio : 2.27.0                                                      *
*       matplotlib : 3.6.3                                                    *
*       networkx : 3.1                                                        *
*       numpy : 1.24.2                                                        *
*       scipy : 1.10.1                                                        *
*                                                                             *
===============================================================================
defaultdict(<class 'dict'>, {'Interpreter': {'python': '3.11.3 (main, Apr  9 2023, 16:36:12) [Clang 10.0.0 (clang-1000.10.44.4)]'}, 'colour-science.org': {'colour': '0.4.2'}, 'Runtime': {'imageio': '2.27.0', 'matplotlib': '3.6.3', 'networkx': '3.1', 'numpy': '1.24.2', 'scipy': '1.10.1'}})
```

**Comment by KelSolaar** [comment]
Hello,

We have updated the signature of the `RGB_to_XYZ` and `XYZ_to_RGB` definitions in *Colour* 0.4.3 which is what you are using but you are on *Colour* 0.4.2. Can you try to upgrade please?

Cheers,

Thomas

**Comment by BQ-Octantis** [comment]
Yay, it works in 0.4.3!

Cheers,

BQ

**Comment by KelSolaar** [comment]
Awesome! Closing this one then! :)
