### ISSUE TITLE
"colour.CAM16_to_XYZ" definition expects "L_A" to be an array_like when "discount_illuminant=True".

### ISSUE THREAD

**Issue by briend** [colour-science/colour#419]
colour 0.3.11
numpy 1.14.0
scipy 1.0.0
python 3.6
```
 illuminant=colour.xy_to_XYZ(colour.ILLUMINANTS['cie_2_1931']['A']) * 100.0
 colour.XYZ_to_sRGB(colour.CAM16_to_XYZ(colour.XYZ_to_CAM16(colour.sRGB_to_XYZ([0,0,1])*100, illuminant, 200, 10, discount_illuminant=True), illuminant, 200, 10, discount_illuminant=True)/100)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python36\lib\site-packages\colour\appearance\cam16.py", line 376, in CAM16_to_XYZ
    if not discount_illuminant else np.ones(L_A.shape))
```
I only need to make one of the L_As into an array to avoid the problem:
```
colour.XYZ_to_sRGB(colour.CAM16_to_XYZ(colour.XYZ_to_CAM16(colour.sRGB_to_XYZ([0,0,1])*100, illuminant, 200, 10, discount_illuminant=True), illuminant, np.array([200]), 10, discount_illuminant=True)/100)
array([[  2.99227200e-04,  -1.02584800e-04,   1.00000156e+00]])
```

**Comment by KelSolaar** [comment]
Cheers,

Will look at that tomorrow, seems straightforward fix! CIECAM02 is likely affected.

**Comment by KelSolaar** [comment]
@briend : This should be fixed, sorry for the lag in making that done!
