### ISSUE TITLE
"TypeError" exception caused by "Numpy" 1.18 in "colour.SpectralShape.range" method.

### ISSUE THREAD

**Issue by AndersAtEndian** [colour-science/colour#541]
Using numpy 1.18.0 (just released) I get a ```TypeError: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer``` when I import colour. 

Creating a new virtual environment.

```
➜  vf new -p ~/.pyenv/versions/3.8.0/bin/python numpy-test                                                                                                            Running virtualenv with interpreter /Users/anders/.pyenv/versions/3.8.0/bin/python
Using base prefix '/Users/anders/.pyenv/versions/3.8.0'
New python executable in /Users/anders/.virtualenvs/numpy-test/bin/python
Installing setuptools, pip, wheel...
done.
```

Install colour.

```
(numpy-test) ➜  pip install colour-science                                                                                                                            Collecting colour-science
  Using cached https://files.pythonhosted.org/packages/0f/5e/d6fb7e115ce3176be3901c62cb01c4189e59058fb0f1b259b54a520ec67c/colour_science-0.3.14-py2.py3-none-any.whl
Collecting scipy
  Using cached https://files.pythonhosted.org/packages/90/d2/44b70a930ad28da8f65d8c294ac88b20f561e5d650b85efea80381566db1/scipy-1.4.1-cp38-cp38-macosx_10_9_x86_64.whl
Collecting imageio
  Using cached https://files.pythonhosted.org/packages/1a/de/f7f985018f462ceeffada7f6e609919fbcc934acd9301929cba14bc2c24a/imageio-2.6.1-py3-none-any.whl
Collecting six
  Using cached https://files.pythonhosted.org/packages/65/26/32b8464df2a97e6dd1b656ed26b2c194606c16fe163c695a992b36c11cdf/six-1.13.0-py2.py3-none-any.whl
Collecting numpy>=1.13.3
  Using cached https://files.pythonhosted.org/packages/85/7c/a870abc411a46b90b3c38b1e609e3bdae97fc87bc4c7e49dc3ac98df36d1/numpy-1.18.0-cp38-cp38-macosx_10_9_x86_64.whl
Collecting pillow
  Using cached https://files.pythonhosted.org/packages/c3/d5/6cf564fe747f573d0a7cd799b24eb9fe9a37500c6d62b56a725e03268a9c/Pillow-6.2.1-cp38-cp38-macosx_10_9_x86_64.whl
Installing collected packages: numpy, scipy, pillow, imageio, six, colour-science
Successfully installed colour-science-0.3.14 imageio-2.6.1 numpy-1.18.0 pillow-6.2.1 scipy-1.4.1 six-1.13.0
```

Trying it out.

```
(numpy-test) ➜  python                                                                                                                                                Python 3.8.0 (default, Dec  5 2019, 14:00:57)
[Clang 11.0.0 (clang-1100.0.33.12)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import colour
Traceback (most recent call last):
  File "/Users/anders/.virtualenvs/numpy-test/lib/python3.8/site-packages/numpy/core/function_base.py", line 117, in linspace
    num = operator.index(num)
TypeError: 'numpy.float64' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/anders/.virtualenvs/numpy-test/lib/python3.8/site-packages/colour/__init__.py", line 139, in <module>
    from .notation import (MUNSELL_COLOURS, MUNSELL_VALUE_METHODS,
  File "/Users/anders/.virtualenvs/numpy-test/lib/python3.8/site-packages/colour/notation/__init__.py", line 12, in <module>
    from .munsell import MUNSELL_VALUE_METHODS
  File "/Users/anders/.virtualenvs/numpy-test/lib/python3.8/site-packages/colour/notation/munsell.py", line 134, in <module>
    from colour.volume import is_within_macadam_limits
  File "/Users/anders/.virtualenvs/numpy-test/lib/python3.8/site-packages/colour/volume/__init__.py", line 10, in <module>
    from .spectrum import (generate_pulse_waves, XYZ_outer_surface,
  File "/Users/anders/.virtualenvs/numpy-test/lib/python3.8/site-packages/colour/volume/spectrum.py", line 133, in <module>
    illuminant=sd_ones(STANDARD_OBSERVERS_CMFS[
  File "/Users/anders/.virtualenvs/numpy-test/lib/python3.8/site-packages/colour/colorimetry/generation.py", line 160, in sd_ones
    return sd_constant(1, shape)
  File "/Users/anders/.virtualenvs/numpy-test/lib/python3.8/site-packages/colour/colorimetry/generation.py", line 94, in sd_constant
    wavelengths = shape.range(dtype)
  File "/Users/anders/.virtualenvs/numpy-test/lib/python3.8/site-packages/colour/colorimetry/spectrum.py", line 455, in range
    range_, current_interval = np.linspace(
  File "<__array_function__ internals>", line 5, in linspace
  File "/Users/anders/.virtualenvs/numpy-test/lib/python3.8/site-packages/numpy/core/function_base.py", line 119, in linspace
    raise TypeError(
TypeError: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.
```

Versions installed. 

```(numpy-test) ➜  pip freeze                                                                                                                                            colour-science==0.3.14
imageio==2.6.1
numpy==1.18.0
Pillow==6.2.1
scipy==1.4.1
six==1.13.0
```

If I revert to numpy 1.17.4 everything works as expected.

**Comment by KelSolaar** [comment]
Hi @AndersAtEndian,

This should be fixed in [develop](https://github.com/colour-science/colour/tree/develop) as per #536.

Cheers,

Thomas
