### ISSUE TITLE
Fix the various "DeprecationWarning" with Python 3.8.

### ISSUE THREAD

**Issue by hajimen** [colour-science/colour#543]
I found two DeprecationWarnings.
`python3.8/site-packages/colour/io/luts/lut.py:20: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working`
`<__array_function__ internals>:5: DeprecationWarning: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.`
Thanks,

**Comment by KelSolaar** [comment]
Thanks @hajimen! I will take a look. Was it on import?

**Comment by hajimen** [comment]
Dockerfile for Amazon Linux 2:
```
FROM amazonlinux:2
ENV HOME /home/hoge
RUN mkdir $HOME
WORKDIR $HOME
RUN curl -O https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
RUN bash Miniconda3-latest-Linux-x86_64.sh -b -p ~/miniconda
ENV PATH $HOME/miniconda/bin:$PATH
RUN conda update -n base -c defaults conda
RUN conda create -y -n python380 python=3.8.0
```

bash:
```
source activate python380
pip install numpy==1.17.4  colour-science==0.3.14
```

Python:
```
import unittest
import numpy as np

class TestTarget(unittest.TestCase):
    def test_delta_e_cie2000(self):
        from colour.difference import delta_E_CIE2000
        r = np.arange(0, 100, 20)
        grid = np.array(np.meshgrid(r, r / 2, r / 2)).T.reshape(-1, 3)
        for lab1 in grid:
            for lab2 in grid:
                d = delta_E_CIE2000(lab1, lab2)
```

It generates:
```
/home/hoge/miniconda/envs/python380/lib/python3.8/site-packages/colour/utilities/data_structures.py:31: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
  from collections import Mapping, MutableMapping
/home/hoge/miniconda/envs/python380/lib/python3.8/site-packages/colour/continuous/signal.py:26: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
  from collections import Iterator, Mapping, Sequence
/home/hoge/miniconda/envs/python380/lib/python3.8/site-packages/colour/io/luts/lut.py:20: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
  from collections import MutableSequence
<__array_function__ internals>:5: DeprecationWarning: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.
```

**Comment by hajimen** [comment]
Overmore, the unittest above fails in numpy==1.18.1.
```
======================================================================
ERROR: test_delta_e_cie2000 (testcs.TestTarget)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Yotsuya\source\repos\venv_doubtdeadlock\lib\site-packages\numpy\core\function_base.py", line 117, in linspace
    num = operator.index(num)
TypeError: 'numpy.float64' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Yotsuya\source\repos\doubtdeadlock\testcs.py", line 11, in test_delta_e_cie2000
    from colour.difference import delta_E_CIE2000
  File "C:\Users\Yotsuya\source\repos\venv_doubtdeadlock\lib\site-packages\colour\__init__.py", line 139, in <module>
    from .notation import (MUNSELL_COLOURS, MUNSELL_VALUE_METHODS,
  File "C:\Users\Yotsuya\source\repos\venv_doubtdeadlock\lib\site-packages\colour\notation\__init__.py", line 12, in <module>
    from .munsell import MUNSELL_VALUE_METHODS
  File "C:\Users\Yotsuya\source\repos\venv_doubtdeadlock\lib\site-packages\colour\notation\munsell.py", line 134, in <module>
    from colour.volume import is_within_macadam_limits
  File "C:\Users\Yotsuya\source\repos\venv_doubtdeadlock\lib\site-packages\colour\volume\__init__.py", line 10, in <module>
    from .spectrum import (generate_pulse_waves, XYZ_outer_surface,
  File "C:\Users\Yotsuya\source\repos\venv_doubtdeadlock\lib\site-packages\colour\volume\spectrum.py", line 133, in <module>
    illuminant=sd_ones(STANDARD_OBSERVERS_CMFS[
  File "C:\Users\Yotsuya\source\repos\venv_doubtdeadlock\lib\site-packages\colour\colorimetry\generation.py", line 160, in sd_ones
    return sd_constant(1, shape)
  File "C:\Users\Yotsuya\source\repos\venv_doubtdeadlock\lib\site-packages\colour\colorimetry\generation.py", line 94, in sd_constant
    wavelengths = shape.range(dtype)
  File "C:\Users\Yotsuya\source\repos\venv_doubtdeadlock\lib\site-packages\colour\colorimetry\spectrum.py", line 455, in range
    range_, current_interval = np.linspace(
  File "<__array_function__ internals>", line 5, in linspace
  File "C:\Users\Yotsuya\source\repos\venv_doubtdeadlock\lib\site-packages\numpy\core\function_base.py", line 119, in linspace
    raise TypeError(
TypeError: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.
```

**Comment by KelSolaar** [comment]
Thanks!
