### ISSUE TITLE
"TypeError" exception raised by "Numpy" 1.18 in "colour.SpectralShape.range" method.

### ISSUE THREAD

**Issue by mokincha** [colour-science/colour#548]
"import colour" fails on a fresh install of Python 3.8.1 and colour-science 0.3.14 using all the current libraries. 

C:\windows\system32>python
Python 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 23:11:46) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import colour
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\site-packages\numpy\core\function_base.py", line 117, in linspace
    num = operator.index(num)
TypeError: 'numpy.float64' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python38\lib\site-packages\colour\__init__.py", line 139, in <module>
    from .notation import (MUNSELL_COLOURS, MUNSELL_VALUE_METHODS,
  File "C:\Program Files\Python38\lib\site-packages\colour\notation\__init__.py", line 12, in <module>
    from .munsell import MUNSELL_VALUE_METHODS
  File "C:\Program Files\Python38\lib\site-packages\colour\notation\munsell.py", line 134, in <module>
    from colour.volume import is_within_macadam_limits
  File "C:\Program Files\Python38\lib\site-packages\colour\volume\__init__.py", line 10, in <module>
    from .spectrum import (generate_pulse_waves, XYZ_outer_surface,
  File "C:\Program Files\Python38\lib\site-packages\colour\volume\spectrum.py", line 133, in <module>
    illuminant=sd_ones(STANDARD_OBSERVERS_CMFS[
  File "C:\Program Files\Python38\lib\site-packages\colour\colorimetry\generation.py", line 160, in sd_ones
    return sd_constant(1, shape)
  File "C:\Program Files\Python38\lib\site-packages\colour\colorimetry\generation.py", line 94, in sd_constant
    wavelengths = shape.range(dtype)
  File "C:\Program Files\Python38\lib\site-packages\colour\colorimetry\spectrum.py", line 455, in range
    range_, current_interval = np.linspace(
  File "<__array_function__ internals>", line 5, in linspace
  File "C:\Program Files\Python38\lib\site-packages\numpy\core\function_base.py", line 119, in linspace
    raise TypeError(
TypeError: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.
>>>

**Comment by KelSolaar** [comment]
Hi @mokincha,

This is resolved in the `develop` branch and I will try to get a new release over the weekend!

Cheers,

Thomas

**Comment by mokincha** [comment]
Library now loads and works as it should.  Much thanks for the excellent support!
